apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-node-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cicd-node-app
  template:
    metadata:
      labels:
        app: cicd-node-app
    spec:
      containers:
      - name: cicd-node-container
        image: karthikeyakashyap/cicd-node-app:latest
        ports:
        - containerPort: 3000
